# PyTorch Auto Grad

自動微分

## 事前準備

In [1]:
import torch

# GPUが使えるか確認してデバイスを設定
# NOTE: `x = x.to(device) ` とすることで対象のデバイスに切り替え可能
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

## 自動微分

In [2]:
import torch
from tqdm.notebook import tqdm

### requires_grad属性

Tensorのrequires_grad属性をTrueにすることで、各要素の勾配が自動微分の計算対象となる。  
また、requires_grad属性をTrueの場合、Tensorの演算をすることで、grad_fnが記録される。

In [3]:
x = torch.ones(2, 3, requires_grad=True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [4]:
y = x + 2
y

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)

### 勾配の自動計算

In [5]:
a = torch.tensor([1.0], requires_grad=True)
b = a * 2

# 逆伝搬
b.backward()

# b = 2 * a をaで微分するため、結果は2となる
a.grad

tensor([2.])